import type { NextPage } from 'next'
import Head from 'next/head'
import styles from '../styles/Home.module.css'
import useSWR from 'swr'
import { fetcher } from '../utils/fetcher'
import { useEffect } from 'react'
import UserNote from '../components/userNote'
import Error from '../components/error'
import Demo from '../components/demo'


const Home: NextPage = () => {

  return (
    <div className={styles.container}>
      <Head>
        <title>Tool Finder</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      {/* <Table data={data} /> */}
      <UserNote />
      {/* <Searchbar /> */}
      <Demo />

    </div>
  )
}

export default Home